# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6132d7df79fd49712460a24f1ee137829f6c7c5fed9763bce17c948c3c8f80f2af6cc4ae0970711f30dc8f76180db9be7a66abe9d56751b24b9ce3cb112931b

test:
  secret_key_base: c4ba5cab4e47004e623f77fa43c0834cd9a37e86c24a98b1b94366608f1340244ea8eef20139efa6ecf68c6833dba5bf3b5093b45ae60ee93761b1e3faace887

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
